# Generated by Django 4.1.1 on 2022-09-22 18:22

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promo', models.IntegerField(unique=True, verbose_name='Номер промокода')),
                ('date', unixtimestampfield.fields.UnixTimeStampField(verbose_name='Дата')),
                ('promo_name', models.TextField(blank=True, verbose_name='название промокода')),
                ('count', models.IntegerField(verbose_name='Количество воспользовавшихся промокодом')),
                ('count_money', models.IntegerField(verbose_name='Сколько заработано на промокоде')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seminar', models.IntegerField(unique=True, verbose_name='Номер семинара')),
                ('money', models.IntegerField(blank=True, verbose_name='Цена без подписки')),
                ('money_sale', models.IntegerField(blank=True, verbose_name='Цена с подпиской')),
                ('date', unixtimestampfield.fields.UnixTimeStampField(verbose_name='Дата')),
                ('description_topic', models.TextField(blank=True, verbose_name='Дополнительное описание')),
                ('descroption_small', models.TextField(verbose_name='Короткое описание')),
                ('descroption', models.TextField(verbose_name='Описание')),
                ('days_3', models.TextField(blank=True, null=True, unique=True, verbose_name='Уведомление за 3 дня')),
                ('hour_1', models.TextField(blank=True, null=True, verbose_name='Уведомление за 1 день')),
                ('minute_15', models.TextField(blank=True, null=True, verbose_name='Уведомление за 15 минут')),
            ],
            options={
                'verbose_name': 'Семинар',
                'verbose_name_plural': 'Семинары',
            },
        ),
    ]
