# Generated by Django 4.1.1 on 2022-09-26 15:41

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promo', models.IntegerField(unique=True, verbose_name='Номер промокода')),
                ('date', models.IntegerField(verbose_name='Дата')),
                ('promo_name', models.TextField(blank=True, verbose_name='название промокода')),
                ('count', models.IntegerField(default=0, verbose_name='Количество воспользовавшихся промокодом')),
                ('count_money', models.IntegerField(default=0, verbose_name='Сколько заработано на промокоде')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
        migrations.CreateModel(
            name='Scraping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField(unique=True, verbose_name='Айди пользователя')),
                ('status_user', models.TextField(default='user', verbose_name='Статус юзер')),
                ('date', models.DateTimeField(blank=True, verbose_name='что то по дате')),
                ('date_start', models.DateTimeField(verbose_name='data')),
                ('date_end', models.IntegerField(default=0, verbose_name='Дата окончания')),
                ('date_remainder', models.DateTimeField(default=0, verbose_name='date_remainder')),
                ('date_remainder_int', models.IntegerField(default=0, verbose_name='date_remainder_int')),
                ('id_add_user', models.IntegerField(default=0, verbose_name='id')),
                ('count', models.IntegerField(default=0, verbose_name='count')),
                ('lastname_name', models.TextField(blank=True, null=True, verbose_name='lastname_name')),
                ('name', models.TextField(blank=True, null=True, verbose_name='name')),
                ('patronymic', models.TextField(blank=True, null=True, verbose_name='patronymic')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='phone')),
                ('e_mail', models.TextField(blank=True, null=True, verbose_name='e_mail')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seminar', models.IntegerField(unique=True, verbose_name='Номер семинара')),
                ('money', models.IntegerField(blank=True, verbose_name='Цена без подписки')),
                ('money_sale', models.IntegerField(blank=True, verbose_name='Цена с подпиской')),
                ('date', unixtimestampfield.fields.UnixTimeStampField(verbose_name='Дата')),
                ('description_topic', models.TextField(blank=True, verbose_name='Дополнительное описание')),
                ('description_small', models.TextField(verbose_name='Короткое описание')),
                ('description', models.TextField(verbose_name='Описание')),
                ('days_3', models.TextField(blank=True, default=None, null=True, verbose_name='Уведомление за 3 дня')),
                ('hour_1', models.TextField(blank=True, default=None, null=True, verbose_name='Уведомление за 1 день')),
                ('minute_15', models.TextField(blank=True, default=None, null=True, verbose_name='Уведомление за 15 минут')),
            ],
            options={
                'verbose_name': 'Семинар',
                'verbose_name_plural': 'Семинары',
            },
        ),
        migrations.CreateModel(
            name='User_promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_promo', models.IntegerField(unique=True, verbose_name='Номер промокода')),
                ('id_user', models.IntegerField(unique=True, verbose_name='Номер юзера')),
            ],
            options={
                'verbose_name': 'Юзер_промокод',
                'verbose_name_plural': 'Юзеры_промокоды',
            },
        ),
        migrations.CreateModel(
            name='User_seminar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_seminar', models.IntegerField(unique=True, verbose_name='Номер промокода')),
                ('id_user', models.IntegerField(unique=True, verbose_name='Номер юзера')),
            ],
            options={
                'verbose_name': 'Юзер_семинар',
                'verbose_name_plural': 'Юзеры_семинар',
            },
        ),
    ]
