# Generated by Django 4.1.1 on 2022-09-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seminar',
            name='days_3',
            field=models.TextField(blank=True, null=True, verbose_name='Уведомление за 3 дня'),
        ),
    ]
