# Generated by Django 4.1.1 on 2022-09-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraping',
            name='date_remainder',
            field=models.DateTimeField(verbose_name='date_remainder'),
        ),
    ]
