# Generated by Django 4.1.1 on 2022-09-28 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_scraping_date_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraping',
            name='chek_about',
            field=models.TextField(blank=True, default='user', verbose_name='проверка'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='days_3',
            field=models.TextField(blank=True, default='no', verbose_name='Уведомление за 3 дня'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='hour_1',
            field=models.TextField(blank=True, default='no', verbose_name='Уведомление за 1 день'),
        ),
        migrations.AlterField(
            model_name='seminar',
            name='minute_15',
            field=models.TextField(blank=True, default='no', verbose_name='Уведомление за 15 минут'),
        ),
    ]
